import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { BookOpen, CheckCircle2, XCircle, Download, Clock, Loader2, Calendar } from "lucide-react";
import type { ParsedResult, StudentInfo } from "@/lib/ktu-api";
import {
  normalizeSemester,
  normalizeSession,
  normalizeSlot,
  parseTimetableCsv,
  type TimetableExamEntry,
} from "@/lib/timetable";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";

interface ResultDisplayProps {
  results: ParsedResult[];
  rawHtml?: string;
  studentInfo?: StudentInfo;
  selectedSemester?: string;
}

type ExamEntry = TimetableExamEntry;

const BUNDLED_TIMETABLE_CSV_PATH = "/data/ktu_btech_exam_schedule_2019_scheme.csv";

function mergeExamEntries(primary: ExamEntry[], fallback: ExamEntry[]): ExamEntry[] {
  // Keep fallback rows, override with primary DB rows for same date+sem+slot+session.
  const merged = new Map<string, ExamEntry>();
  const put = (entry: ExamEntry) => {
    const key = `${entry.date}|${entry.semester}|${normalizeSlot(entry.slot)}|${normalizeSession(entry.session)}`;
    merged.set(key, entry);
  };

  fallback.forEach(put);
  primary.forEach(put);

  return Array.from(merged.values()).sort((a, b) => a.date.localeCompare(b.date));
}

function getSequentialSlotByOrder(orderIndex: number): string {
  if (!Number.isFinite(orderIndex) || orderIndex < 0) return "";
  const ascii = "A".charCodeAt(0) + orderIndex;
  // Supports A-Z; beyond that, keep empty instead of showing invalid labels.
  if (ascii > "Z".charCodeAt(0)) return "";
  return String.fromCharCode(ascii);
}

function getGradeColor(grade: string): string {
  const g = grade.trim().toUpperCase();
  if (g === 'S') return 'bg-emerald-600 text-white';
  if (g === 'A+') return 'bg-green-500 text-white';
  if (g === 'A') return 'bg-teal-500 text-white';
  if (g === 'B+') return 'bg-sky-500 text-white';
  if (g === 'B') return 'bg-blue-500 text-white';
  if (g === 'C+') return 'bg-amber-500 text-white';
  if (g === 'C') return 'bg-orange-500 text-white';
  if (g === 'D' || g === 'P') return 'bg-yellow-600 text-white';
  if (g === 'F' || g === 'FE') return 'bg-destructive text-destructive-foreground';
  return 'bg-secondary text-secondary-foreground';
}

function isPassed(grade: string): boolean {
  const g = grade.trim().toUpperCase();
  const VALID_PASS = new Set(['S', 'A+', 'A', 'B+', 'B', 'C+', 'C', 'D', 'P']);
  return VALID_PASS.has(g);
}

function isReviewPending(result: ParsedResult): boolean {
  const details = (result.examDetails || '').toLowerCase();
  const grade = result.grade.toUpperCase();
  // Review requested OR no grade yet (result coming soon)
  return details.includes('review') || details.includes('reval') || details.includes('pending')
    || (grade === '' && details !== '');
}

function isFailed(grade: string): boolean {
  const g = grade.trim().toUpperCase();
  return g === 'F' || g === 'FE';
}

function isResultComingSoon(result: ParsedResult): boolean {
  const grade = result.grade.trim().toUpperCase();
  // Coming soon = anything that's not a passing grade and not an explicit fail
  return !isPassed(grade) && !isFailed(grade);
}

function downloadPDF(results: ParsedResult[], studentInfo?: StudentInfo, semester?: string) {
  const doc = new jsPDF();

  // Title
  doc.setFontSize(16);
  doc.text('KTU Examination Results', 14, 20);

  // Student info
  doc.setFontSize(10);
  let y = 30;
  if (studentInfo?.name) { doc.text(`Name: ${studentInfo.name}`, 14, y); y += 6; }
  if (studentInfo?.registerNumber) { doc.text(`Register No: ${studentInfo.registerNumber}`, 14, y); y += 6; }
  if (studentInfo?.branch) { doc.text(`Branch: ${studentInfo.branch}`, 14, y); y += 6; }
  if (semester) { doc.text(`Semester: ${semester}`, 14, y); y += 6; }
  if (studentInfo?.cgpa) { doc.text(`CGPA: ${studentInfo.cgpa}`, 14, y); y += 6; }

  y += 4;

  // Table
  autoTable(doc, {
    startY: y,
    head: [['Code', 'Course', 'Credits', 'Grade', 'Status']],
    body: results.map(r => [
      r.code,
      r.courseName,
      r.credits,
      r.grade,
      isPassed(r.grade) ? 'Pass' : (isFailed(r.grade) ? 'Fail' : 'Pending'),
    ]),
    styles: { fontSize: 8 },
    headStyles: { fillColor: [41, 128, 185] },
  });

  doc.setFontSize(8);
  doc.text('Generated by My KTU Pro', 14, doc.internal.pageSize.height - 10);

  const fileName = `KTU_Results_${studentInfo?.registerNumber || 'student'}_${semester || ''}.pdf`;
  doc.save(fileName);
}

export function ResultDisplay({ results, rawHtml, studentInfo, selectedSemester }: ResultDisplayProps) {
  const [exams, setExams] = useState<ExamEntry[]>([]);
  const [isLoadingExams, setIsLoadingExams] = useState(false);
  const [showFailedOnly, setShowFailedOnly] = useState(false);

  useEffect(() => {
    const fetchExams = async () => {
      setIsLoadingExams(true);
      const today = new Date().toISOString().split('T')[0];
      const [dbResult, fallbackCsvText] = await Promise.all([
        supabase
          .from('exam_timetable')
          .select('id, date, day, session, slot, semester, subject_code')
          .gte('date', today)
          .order('date', { ascending: true }),
        fetch(BUNDLED_TIMETABLE_CSV_PATH)
          .then((r) => (r.ok ? r.text() : ""))
          .catch(() => ""),
      ]);

      const dbRows: ExamEntry[] =
        !dbResult.error && dbResult.data
          ? (dbResult.data as ExamEntry[]).map((row) => ({
              ...row,
              semester: normalizeSemester(row.semester),
              slot: normalizeSlot(row.slot),
              session: normalizeSession(row.session),
              subject_code: row.subject_code ? row.subject_code.trim().toUpperCase() : "",
            }))
          : [];

      const fallbackRows = fallbackCsvText
        ? parseTimetableCsv(fallbackCsvText).rows.filter((e) => e.date >= today)
        : [];

      setExams(mergeExamEntries(dbRows, fallbackRows));
      setIsLoadingExams(false);
    };

    // Only fetch if there are failed subjects or coming soon subjects in this semester
    if (results.some(r => isFailed(r.grade) || isResultComingSoon(r))) {
      fetchExams();
    } else {
      setExams([]);
    }
  }, [results]);

  const ktuSubjectSlots: Record<string, string> = {
    // S1 & S2 Common
    "MAT101": "A", "PHT110": "B", "CYT100": "B", "EST100": "C", "EST110": "C",
    "EST120": "D", "EST130": "D", "HUN101": "E", "MAT102": "A", "HUN102": "E", "EST102": "F",
    // S3
    "MAT201": "A", "CET201": "B", "CET203": "C", "CET205": "D", "EST200": "E", "HUT200": "E", "MCN201": "F",
    // S4
    "MAT202": "A", "CET202": "B", "CET204": "C", "CET206": "D", "MCN202": "F",
    // S5
    "CET301": "A", "CET303": "B", "CET305": "C", "CET307": "D", "CET309": "E", "MCN301": "F",
    // S6
    "CET302": "A", "CET304": "B", "CET306": "C", "HUT300": "E", "CET308": "F",
    // S7
    "CET401": "A", "MCN401": "D",
    // S8
    "CET402": "A", "CET404": "E"
  };

  const getDisplaySlotForSubject = (
    result: ParsedResult,
    examDetails?: { slot?: string } | null,
    orderIndex?: number
  ) => {
    const parsedSlot = normalizeSlot(result.slot);
    if (parsedSlot) return parsedSlot;

    const examSlot = normalizeSlot(examDetails?.slot);
    if (examSlot) return examSlot;

    const fallbackSlot = ktuSubjectSlots[result.code.trim().toUpperCase()];
    if (normalizeSlot(fallbackSlot)) return normalizeSlot(fallbackSlot);

    // Final fallback requested: assign slots in displayed subject order (A, B, C, ...).
    return getSequentialSlotByOrder(orderIndex ?? -1);
  };

  const getExamDetailsForSubject = (result: ParsedResult) => {
    const subjectCode = result.code;
    // 1. Try exact subject_code match first
    const exactMatch = exams.find(e =>
      e.subject_code && e.subject_code.trim().toUpperCase() === subjectCode.trim().toUpperCase()
    );
    if (exactMatch) {
      const d = new Date(exactMatch.date);
      return {
        ...exactMatch,
        formattedDate: d.toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })
      };
    }

    // 2. Prefer actual slot parsed from KTU result table for this specific subject
    if (selectedSemester && normalizeSlot(result.slot)) {
      const slotMatch = exams.find(e =>
        normalizeSemester(e.semester) === normalizeSemester(selectedSemester) &&
        normalizeSlot(e.slot) === normalizeSlot(result.slot)
      );
      if (slotMatch) {
        const d = new Date(slotMatch.date);
        return {
          ...slotMatch,
          formattedDate: d.toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })
        };
      }
    }

    // 3. Legacy fallback: Use static subject-slot mapping
    if (selectedSemester) {
      const expectedSlot = ktuSubjectSlots[subjectCode.trim().toUpperCase()];

      if (expectedSlot) {
        const slotMatch = exams.find(e =>
          normalizeSemester(e.semester) === normalizeSemester(selectedSemester) &&
          normalizeSlot(e.slot) === expectedSlot
        );
        if (slotMatch) {
          const d = new Date(slotMatch.date);
          return {
            ...slotMatch,
            formattedDate: d.toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })
          };
        }
      }
    }

    return null;
  };

  if (results.length === 0 && rawHtml) {
    return (
      <Card className="shadow-lg border-0">
        <CardHeader className="pb-3 pt-4 px-4">
          <CardTitle className="flex items-center gap-2 text-base">
            <BookOpen className="h-5 w-5 text-primary" />
            Result Page Content
          </CardTitle>
        </CardHeader>
        <CardContent className="px-4 pb-4">
          <div
            className="prose prose-sm max-w-none overflow-auto max-h-[600px] border rounded-lg p-4 bg-muted/30"
            dangerouslySetInnerHTML={{ __html: rawHtml }}
          />
        </CardContent>
      </Card>
    );
  }

  if (results.length === 0) return null;

  const displayedResults = showFailedOnly ? results.filter(r => isFailed(r.grade)) : results;

  return (
    <Card className="shadow-lg border-0 overflow-hidden">
      <CardHeader className="pb-3 pt-4 px-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <CardTitle className="flex items-center gap-2 text-base">
            <BookOpen className="h-5 w-5 text-primary" />
            Semester Results
          </CardTitle>
          <div className="flex items-center gap-4 self-end sm:self-auto">
            <div className="flex items-center space-x-2">
              <Switch
                id="show-failed"
                checked={showFailedOnly}
                onCheckedChange={setShowFailedOnly}
              />
              <Label htmlFor="show-failed" className="text-xs cursor-pointer">
                Show Failed Only
              </Label>
            </div>
            <Button
              variant="outline"
              size="sm"
              onClick={() => downloadPDF(results, studentInfo, selectedSemester)}
              className="text-xs h-8"
            >
              <Download className="h-3.5 w-3.5 mr-1.5" />
              PDF
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent className="px-4 pb-4">
        {displayedResults.length === 0 && showFailedOnly ? (
          <p className="text-sm text-muted-foreground py-4 text-center">
            No failed subjects in this semester! 🎉
          </p>
        ) : (
          <Accordion type="single" collapsible className="space-y-2">
            {displayedResults.map((r, i) => {
              const passed = isPassed(r.grade);
              const reviewPending = isReviewPending(r);
              const comingSoon = isResultComingSoon(r);
              const isFail = isFailed(r.grade);
              const needsExamDetails = isFail || comingSoon;
              const examDetails = getExamDetailsForSubject(r);
              const displaySlot = getDisplaySlotForSubject(r, examDetails, i);

              return (
                <AccordionItem
                  key={i}
                  value={`item-${i}`}
                  className="border-0 bg-muted/50 rounded-lg overflow-hidden transition-colors data-[state=closed]:hover:bg-muted"
                >
                  <AccordionTrigger className="hover:no-underline p-3 gap-3">
                    <div className="flex items-start sm:items-center gap-3 flex-1 text-left">
                      <div className={`flex-shrink-0 mt-0.5 sm:mt-0 ${comingSoon ? 'text-warning' : passed ? 'text-success' : 'text-destructive'}`}>
                        {comingSoon ? <Loader2 className="h-5 w-5 animate-spin" /> : passed ? <CheckCircle2 className="h-5 w-5" /> : <XCircle className="h-5 w-5" />}
                      </div>
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium leading-tight sm:truncate">{r.courseName}</p>
                        <div className="flex items-center gap-2 flex-wrap mt-1">
                          <p className="text-xs text-muted-foreground">{r.code}</p>
                          {displaySlot && (
                            <Badge variant="outline" className="text-[10px] leading-none px-1.5 py-0.5">
                              Slot {displaySlot}
                            </Badge>
                          )}
                          {needsExamDetails && examDetails && (
                            <Badge variant={isFail ? "destructive" : "secondary"} className={`text-[10px] font-medium leading-none px-1.5 py-0.5 ${comingSoon ? 'bg-orange-500/10 text-orange-500 border-orange-500/20' : ''}`}>
                              <Calendar className="h-3 w-3 mr-1 inline" />
                              {examDetails.formattedDate}
                            </Badge>
                          )}
                          {needsExamDetails && !examDetails && !isLoadingExams && (
                            <span className="text-[10px] text-muted-foreground italic">
                              No exam date posted
                            </span>
                          )}
                          {needsExamDetails && isLoadingExams && (
                            <span className="text-[10px] text-muted-foreground flex items-center">
                              <Loader2 className="h-3 w-3 animate-spin mr-1" /> Checking dates...
                            </span>
                          )}
                          {reviewPending && (
                            <span className="inline-flex items-center gap-1 text-[10px] font-medium text-warning">
                              <Clock className="h-3 w-3" />
                              Review Requested
                            </span>
                          )}
                          {comingSoon && !reviewPending && (
                            <span className="inline-flex items-center gap-1 text-[10px] font-medium text-info">
                              Result Coming Soon
                            </span>
                          )}
                        </div>
                      </div>
                      <div className="ml-auto flex items-center gap-2 self-start sm:self-center">
                        {r.grade.trim() ? (
                          <Badge className={`${getGradeColor(r.grade)} font-bold text-xs`}>
                            {r.grade}
                          </Badge>
                        ) : (
                          <Badge className="bg-muted text-muted-foreground font-bold text-xs">
                            —
                          </Badge>
                        )}
                        <span className="text-xs text-muted-foreground w-6 text-right hidden sm:inline-block">{r.credits} Cr</span>
                      </div>
                    </div>
                  </AccordionTrigger>

                  <AccordionContent className="px-3 pb-3 pt-0">
                    <div className="ml-[44px] pt-1 mt-1 border-t border-border/50">
                      {examDetails ? (
                        <div className="grid grid-cols-2 gap-2 mt-2">
                          <div>
                            <p className="text-[10px] text-muted-foreground">Exam Date</p>
                            <p className="text-sm font-medium">{examDetails.formattedDate}</p>
                          </div>
                          <div>
                            <p className="text-[10px] text-muted-foreground">Day</p>
                            <p className="text-sm font-medium">{examDetails.day || '—'}</p>
                          </div>
                          <div>
                            <p className="text-[10px] text-muted-foreground">Session</p>
                            <p className="text-sm font-medium text-primary">
                              {examDetails.session === 'FN' ? '🌅 Forenoon' : examDetails.session === 'AN' ? '🌆 Afternoon' : examDetails.session || '—'}
                            </p>
                          </div>
                          <div>
                            <p className="text-[10px] text-muted-foreground">Slot</p>
                            <p className="text-sm font-medium">{displaySlot || examDetails.slot || '—'}</p>
                          </div>
                        </div>
                      ) : needsExamDetails ? (
                        <div className="py-2 text-center text-sm text-muted-foreground">
                          {isLoadingExams ? 'Checking timetable...' : 'No upcoming exam scheduled for this subject yet.'}
                        </div>
                      ) : (
                        <div className="py-2 text-sm text-muted-foreground flex justify-between">
                          <span>Credits: <strong>{r.credits}</strong></span>
                          {r.earnedCredit && <span>Earned: <strong>{r.earnedCredit}</strong></span>}
                          {passed && <span className="text-success">Passed</span>}
                        </div>
                      )}
                    </div>
                  </AccordionContent>
                </AccordionItem>
              );
            })}
          </Accordion>
        )}
      </CardContent>
    </Card>
  );
}
